version: '3.8'

services:
  postgres:
    image: postgres:15.3
    build: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Northwind
    ports:
      - "5434:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: localhost
    #restart: always
    build: rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: JavaProject/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Northwind
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq


volumes:
  scripts:

